// Autogenerated by Frugal Compiler (3.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

library frugal_test;

export 'src/f_frugal_test_constants.dart' show FrugalTestConstants;
export 'src/f_event.dart' show Event;
export 'src/f_bonk.dart' show Bonk;
export 'src/f_xtruct.dart' show Xtruct;
export 'src/f_xtruct2.dart' show Xtruct2;
export 'src/f_insanity.dart' show Insanity;
export 'src/f_xception.dart' show Xception;
export 'src/f_xception2.dart' show Xception2;
export 'src/f_numberz.dart' show Numberz, serializeNumberz, deserializeNumberz;

export 'src/f_super_service_service.dart' show FSuperService, FSuperServiceClient, fSuperServiceClientFactory;
export 'src/f_frugal_test_service.dart' show FFrugalTest, FFrugalTestClient, fFrugalTestClientFactory;
export 'src/f_events_scope.dart' show EventsPublisher, EventsSubscriber, eventsPublisherFactory, eventsSubscriberFactory;
