/**
 * Autogenerated by Frugal Compiler (3.7.1)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package variety.java;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.util.Objects;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EventWrapper implements org.apache.thrift.TBase<EventWrapper, EventWrapper._Fields>, java.io.Serializable, Cloneable, Comparable<EventWrapper> {
	private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EventWrapper");

	private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("ID", org.apache.thrift.protocol.TType.I64, (short)1);
	private static final org.apache.thrift.protocol.TField EV_FIELD_DESC = new org.apache.thrift.protocol.TField("Ev", org.apache.thrift.protocol.TType.STRUCT, (short)2);
	private static final org.apache.thrift.protocol.TField EVENTS_FIELD_DESC = new org.apache.thrift.protocol.TField("Events", org.apache.thrift.protocol.TType.LIST, (short)3);
	private static final org.apache.thrift.protocol.TField EVENTS2_FIELD_DESC = new org.apache.thrift.protocol.TField("Events2", org.apache.thrift.protocol.TType.SET, (short)4);
	private static final org.apache.thrift.protocol.TField EVENT_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("EventMap", org.apache.thrift.protocol.TType.MAP, (short)5);
	private static final org.apache.thrift.protocol.TField NUMS_FIELD_DESC = new org.apache.thrift.protocol.TField("Nums", org.apache.thrift.protocol.TType.LIST, (short)6);
	private static final org.apache.thrift.protocol.TField ENUMS_FIELD_DESC = new org.apache.thrift.protocol.TField("Enums", org.apache.thrift.protocol.TType.LIST, (short)7);
	private static final org.apache.thrift.protocol.TField A_BOOL_FIELD_FIELD_DESC = new org.apache.thrift.protocol.TField("aBoolField", org.apache.thrift.protocol.TType.BOOL, (short)8);
	private static final org.apache.thrift.protocol.TField A_UNION_FIELD_DESC = new org.apache.thrift.protocol.TField("a_union", org.apache.thrift.protocol.TType.STRUCT, (short)9);
	private static final org.apache.thrift.protocol.TField TYPEDEF_OF_TYPEDEF_FIELD_DESC = new org.apache.thrift.protocol.TField("typedefOfTypedef", org.apache.thrift.protocol.TType.STRING, (short)10);
	private static final org.apache.thrift.protocol.TField DEPR_FIELD_DESC = new org.apache.thrift.protocol.TField("depr", org.apache.thrift.protocol.TType.BOOL, (short)11);
	private static final org.apache.thrift.protocol.TField DEPR_BINARY_FIELD_DESC = new org.apache.thrift.protocol.TField("deprBinary", org.apache.thrift.protocol.TType.STRING, (short)12);
	private static final org.apache.thrift.protocol.TField DEPR_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("deprList", org.apache.thrift.protocol.TType.LIST, (short)13);
	private static final org.apache.thrift.protocol.TField EVENTS_DEFAULT_FIELD_DESC = new org.apache.thrift.protocol.TField("EventsDefault", org.apache.thrift.protocol.TType.LIST, (short)14);
	private static final org.apache.thrift.protocol.TField EVENT_MAP_DEFAULT_FIELD_DESC = new org.apache.thrift.protocol.TField("EventMapDefault", org.apache.thrift.protocol.TType.MAP, (short)15);
	private static final org.apache.thrift.protocol.TField EVENT_SET_DEFAULT_FIELD_DESC = new org.apache.thrift.protocol.TField("EventSetDefault", org.apache.thrift.protocol.TType.SET, (short)16);

	public long ID; // optional
	public Event Ev; // required
	public java.util.List<Event> Events;
	public java.util.Set<Event> Events2;
	public java.util.Map<Long, Event> EventMap;
	public java.util.List<java.util.List<Integer>> Nums;
	public java.util.List<ItsAnEnum> Enums;
	public boolean aBoolField;
	public TestingUnions a_union;
	public String typedefOfTypedef;
	/**
	 * This is a docstring comment for a deprecated field that has been spread
	 * across two lines.
	 * @deprecated use something else
	 */
	@Deprecated
	public boolean depr;
	/**
	 * @deprecated use something else
	 */
	@Deprecated
	public java.nio.ByteBuffer deprBinary;
	/**
	 * @deprecated use something else
	 */
	@Deprecated
	public java.util.List<Boolean> deprList;
	public java.util.List<Event> EventsDefault; // optional
	public java.util.Map<Long, Event> EventMapDefault; // optional
	public java.util.Set<Event> EventSetDefault; // optional
	/** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
	public enum _Fields implements org.apache.thrift.TFieldIdEnum {
		ID((short)1, "ID"),
		EV((short)2, "Ev"),
		EVENTS((short)3, "Events"),
		EVENTS2((short)4, "Events2"),
		EVENT_MAP((short)5, "EventMap"),
		NUMS((short)6, "Nums"),
		ENUMS((short)7, "Enums"),
		A_BOOL_FIELD((short)8, "aBoolField"),
		A_UNION((short)9, "a_union"),
		TYPEDEF_OF_TYPEDEF((short)10, "typedefOfTypedef"),
		/**
		 * This is a docstring comment for a deprecated field that has been spread
		 * across two lines.
		 */
		DEPR((short)11, "depr"),
		DEPR_BINARY((short)12, "deprBinary"),
		DEPR_LIST((short)13, "deprList"),
		EVENTS_DEFAULT((short)14, "EventsDefault"),
		EVENT_MAP_DEFAULT((short)15, "EventMapDefault"),
		EVENT_SET_DEFAULT((short)16, "EventSetDefault")
		;

		private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

		static {
			for (_Fields field : EnumSet.allOf(_Fields.class)) {
				byName.put(field.getFieldName(), field);
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, or null if its not found.
		 */
		public static _Fields findByThriftId(int fieldId) {
			switch(fieldId) {
				case 1: // ID
					return ID;
				case 2: // EV
					return EV;
				case 3: // EVENTS
					return EVENTS;
				case 4: // EVENTS2
					return EVENTS2;
				case 5: // EVENT_MAP
					return EVENT_MAP;
				case 6: // NUMS
					return NUMS;
				case 7: // ENUMS
					return ENUMS;
				case 8: // A_BOOL_FIELD
					return A_BOOL_FIELD;
				case 9: // A_UNION
					return A_UNION;
				case 10: // TYPEDEF_OF_TYPEDEF
					return TYPEDEF_OF_TYPEDEF;
				case 11: // DEPR
					return DEPR;
				case 12: // DEPR_BINARY
					return DEPR_BINARY;
				case 13: // DEPR_LIST
					return DEPR_LIST;
				case 14: // EVENTS_DEFAULT
					return EVENTS_DEFAULT;
				case 15: // EVENT_MAP_DEFAULT
					return EVENT_MAP_DEFAULT;
				case 16: // EVENT_SET_DEFAULT
					return EVENT_SET_DEFAULT;
				default:
					return null;
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, throwing an exception
		 * if it is not found.
		 */
		public static _Fields findByThriftIdOrThrow(int fieldId) {
			_Fields fields = findByThriftId(fieldId);
			if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
			return fields;
		}

		/**
		 * Find the _Fields constant that matches name, or null if its not found.
		 */
		public static _Fields findByName(String name) {
			return byName.get(name);
		}

		private final short _thriftId;
		private final String _fieldName;

		_Fields(short thriftId, String fieldName) {
			_thriftId = thriftId;
			_fieldName = fieldName;
		}

		public short getThriftFieldId() {
			return _thriftId;
		}

		public String getFieldName() {
			return _fieldName;
		}
	}

	// isset id assignments
	private static final int __ID_ISSET_ID = 0;
	private static final int __ABOOLFIELD_ISSET_ID = 1;
	private static final int __DEPR_ISSET_ID = 2;
	private byte __isset_bitfield = 0;
	public EventWrapper() {
		this.EventsDefault = new ArrayList<Event>();

		this.EventMapDefault = new HashMap<Long,Event>();

		this.EventSetDefault = new HashSet<Event>();

	}

	public EventWrapper(
		Event Ev,
		java.util.List<Event> Events,
		java.util.Set<Event> Events2,
		java.util.Map<Long, Event> EventMap,
		java.util.List<java.util.List<Integer>> Nums,
		java.util.List<ItsAnEnum> Enums,
		boolean aBoolField,
		TestingUnions a_union,
		String typedefOfTypedef,
		boolean depr,
		java.nio.ByteBuffer deprBinary,
		java.util.List<Boolean> deprList) {
		this();
		this.Ev = Ev;
		this.Events = Events;
		this.Events2 = Events2;
		this.EventMap = EventMap;
		this.Nums = Nums;
		this.Enums = Enums;
		this.aBoolField = aBoolField;
		setABoolFieldIsSet(true);
		this.a_union = a_union;
		this.typedefOfTypedef = typedefOfTypedef;
		this.depr = depr;
		setDeprIsSet(true);
		this.deprBinary = org.apache.thrift.TBaseHelper.copyBinary(deprBinary);
		this.deprList = deprList;
	}

	/**
	 * Performs a deep copy on <i>other</i>.
	 */
	public EventWrapper(EventWrapper other) {
		__isset_bitfield = other.__isset_bitfield;
		this.ID = other.ID;
		if (other.isSetEv()) {
			this.Ev = new Event(other.Ev);
		}
		if (other.isSetEvents()) {
			this.Events = new ArrayList<Event>(other.Events.size());
			for (Event elem52 : other.Events) {
				Event elem53 = new Event(elem52);
				this.Events.add(elem53);
			}
		}
		if (other.isSetEvents2()) {
			this.Events2 = new HashSet<Event>(other.Events2.size());
			for (Event elem54 : other.Events2) {
				Event elem55 = new Event(elem54);
				this.Events2.add(elem55);
			}
		}
		if (other.isSetEventMap()) {
			this.EventMap = new HashMap<Long,Event>(other.EventMap.size());
			for (Map.Entry<Long, Event> elem56 : other.EventMap.entrySet()) {
				long elem58 = elem56.getKey();
				Event elem57 = new Event(elem56.getValue());
				this.EventMap.put(elem58, elem57);
			}
		}
		if (other.isSetNums()) {
			this.Nums = new ArrayList<java.util.List<Integer>>(other.Nums.size());
			for (java.util.List<Integer> elem59 : other.Nums) {
				java.util.List<Integer> elem60 = new ArrayList<Integer>(elem59.size());
				for (int elem61 : elem59) {
					int elem62 = elem61;
					elem60.add(elem62);
				}
				this.Nums.add(elem60);
			}
		}
		if (other.isSetEnums()) {
			this.Enums = new ArrayList<ItsAnEnum>(other.Enums.size());
			for (ItsAnEnum elem63 : other.Enums) {
				ItsAnEnum elem64 = elem63;
				this.Enums.add(elem64);
			}
		}
		this.aBoolField = other.aBoolField;
		if (other.isSetA_union()) {
			this.a_union = new TestingUnions(other.a_union);
		}
		if (other.isSetTypedefOfTypedef()) {
			this.typedefOfTypedef = other.typedefOfTypedef;
		}
		this.depr = other.depr;
		if (other.isSetDeprBinary()) {
			this.deprBinary = org.apache.thrift.TBaseHelper.copyBinary(other.deprBinary);
		}
		if (other.isSetDeprList()) {
			this.deprList = new ArrayList<Boolean>(other.deprList.size());
			for (boolean elem65 : other.deprList) {
				boolean elem66 = elem65;
				this.deprList.add(elem66);
			}
		}
		if (other.isSetEventsDefault()) {
			this.EventsDefault = new ArrayList<Event>(other.EventsDefault.size());
			for (Event elem67 : other.EventsDefault) {
				Event elem68 = new Event(elem67);
				this.EventsDefault.add(elem68);
			}
		}
		if (other.isSetEventMapDefault()) {
			this.EventMapDefault = new HashMap<Long,Event>(other.EventMapDefault.size());
			for (Map.Entry<Long, Event> elem69 : other.EventMapDefault.entrySet()) {
				long elem71 = elem69.getKey();
				Event elem70 = new Event(elem69.getValue());
				this.EventMapDefault.put(elem71, elem70);
			}
		}
		if (other.isSetEventSetDefault()) {
			this.EventSetDefault = new HashSet<Event>(other.EventSetDefault.size());
			for (Event elem72 : other.EventSetDefault) {
				Event elem73 = new Event(elem72);
				this.EventSetDefault.add(elem73);
			}
		}
	}

	public EventWrapper deepCopy() {
		return new EventWrapper(this);
	}

	@Override
	public void clear() {
		setIDIsSet(false);
		this.ID = 0L;

		this.Ev = null;

		this.Events = null;

		this.Events2 = null;

		this.EventMap = null;

		this.Nums = null;

		this.Enums = null;

		setABoolFieldIsSet(false);
		this.aBoolField = false;

		this.a_union = null;

		this.typedefOfTypedef = null;

		setDeprIsSet(false);
		this.depr = false;

		this.deprBinary = null;

		this.deprList = null;

		this.EventsDefault = new ArrayList<Event>();

		this.EventMapDefault = new HashMap<Long,Event>();

		this.EventSetDefault = new HashSet<Event>();

	}

	public long getID() {
		return this.ID;
	}

	public EventWrapper setID(long ID) {
		this.ID = ID;
		setIDIsSet(true);
		return this;
	}

	public void unsetID() {
		__isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
	}

	/** Returns true if field ID is set (has been assigned a value) and false otherwise */
	public boolean isSetID() {
		return EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
	}

	public void setIDIsSet(boolean value) {
		__isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
	}

	public Event getEv() {
		return this.Ev;
	}

	public EventWrapper setEv(Event Ev) {
		this.Ev = Ev;
		return this;
	}

	public void unsetEv() {
		this.Ev = null;
	}

	/** Returns true if field Ev is set (has been assigned a value) and false otherwise */
	public boolean isSetEv() {
		return this.Ev != null;
	}

	public void setEvIsSet(boolean value) {
		if (!value) {
			this.Ev = null;
		}
	}

	public int getEventsSize() {
		return (this.Events == null) ? 0 : this.Events.size();
	}

	public java.util.Iterator<Event> getEventsIterator() {
		return (this.Events == null) ? null : this.Events.iterator();
	}

	public void addToEvents(Event elem) {
		if (this.Events == null) {
			this.Events = new ArrayList<Event>();
		}
		this.Events.add(elem);
	}

	public java.util.List<Event> getEvents() {
		return this.Events;
	}

	public EventWrapper setEvents(java.util.List<Event> Events) {
		this.Events = Events;
		return this;
	}

	public void unsetEvents() {
		this.Events = null;
	}

	/** Returns true if field Events is set (has been assigned a value) and false otherwise */
	public boolean isSetEvents() {
		return this.Events != null;
	}

	public void setEventsIsSet(boolean value) {
		if (!value) {
			this.Events = null;
		}
	}

	public int getEvents2Size() {
		return (this.Events2 == null) ? 0 : this.Events2.size();
	}

	public java.util.Iterator<Event> getEvents2Iterator() {
		return (this.Events2 == null) ? null : this.Events2.iterator();
	}

	public void addToEvents2(Event elem) {
		if (this.Events2 == null) {
			this.Events2 = new HashSet<Event>();
		}
		this.Events2.add(elem);
	}

	public java.util.Set<Event> getEvents2() {
		return this.Events2;
	}

	public EventWrapper setEvents2(java.util.Set<Event> Events2) {
		this.Events2 = Events2;
		return this;
	}

	public void unsetEvents2() {
		this.Events2 = null;
	}

	/** Returns true if field Events2 is set (has been assigned a value) and false otherwise */
	public boolean isSetEvents2() {
		return this.Events2 != null;
	}

	public void setEvents2IsSet(boolean value) {
		if (!value) {
			this.Events2 = null;
		}
	}

	public int getEventMapSize() {
		return (this.EventMap == null) ? 0 : this.EventMap.size();
	}

	public void putToEventMap(long key, Event val) {
		if (this.EventMap == null) {
			this.EventMap = new HashMap<Long,Event>();
		}
		this.EventMap.put(key, val);
	}

	public java.util.Map<Long, Event> getEventMap() {
		return this.EventMap;
	}

	public EventWrapper setEventMap(java.util.Map<Long, Event> EventMap) {
		this.EventMap = EventMap;
		return this;
	}

	public void unsetEventMap() {
		this.EventMap = null;
	}

	/** Returns true if field EventMap is set (has been assigned a value) and false otherwise */
	public boolean isSetEventMap() {
		return this.EventMap != null;
	}

	public void setEventMapIsSet(boolean value) {
		if (!value) {
			this.EventMap = null;
		}
	}

	public int getNumsSize() {
		return (this.Nums == null) ? 0 : this.Nums.size();
	}

	public java.util.Iterator<java.util.List<Integer>> getNumsIterator() {
		return (this.Nums == null) ? null : this.Nums.iterator();
	}

	public void addToNums(java.util.List<Integer> elem) {
		if (this.Nums == null) {
			this.Nums = new ArrayList<java.util.List<Integer>>();
		}
		this.Nums.add(elem);
	}

	public java.util.List<java.util.List<Integer>> getNums() {
		return this.Nums;
	}

	public EventWrapper setNums(java.util.List<java.util.List<Integer>> Nums) {
		this.Nums = Nums;
		return this;
	}

	public void unsetNums() {
		this.Nums = null;
	}

	/** Returns true if field Nums is set (has been assigned a value) and false otherwise */
	public boolean isSetNums() {
		return this.Nums != null;
	}

	public void setNumsIsSet(boolean value) {
		if (!value) {
			this.Nums = null;
		}
	}

	public int getEnumsSize() {
		return (this.Enums == null) ? 0 : this.Enums.size();
	}

	public java.util.Iterator<ItsAnEnum> getEnumsIterator() {
		return (this.Enums == null) ? null : this.Enums.iterator();
	}

	public void addToEnums(ItsAnEnum elem) {
		if (this.Enums == null) {
			this.Enums = new ArrayList<ItsAnEnum>();
		}
		this.Enums.add(elem);
	}

	public java.util.List<ItsAnEnum> getEnums() {
		return this.Enums;
	}

	public EventWrapper setEnums(java.util.List<ItsAnEnum> Enums) {
		this.Enums = Enums;
		return this;
	}

	public void unsetEnums() {
		this.Enums = null;
	}

	/** Returns true if field Enums is set (has been assigned a value) and false otherwise */
	public boolean isSetEnums() {
		return this.Enums != null;
	}

	public void setEnumsIsSet(boolean value) {
		if (!value) {
			this.Enums = null;
		}
	}

	public boolean isABoolField() {
		return this.aBoolField;
	}

	public EventWrapper setABoolField(boolean aBoolField) {
		this.aBoolField = aBoolField;
		setABoolFieldIsSet(true);
		return this;
	}

	public void unsetABoolField() {
		__isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ABOOLFIELD_ISSET_ID);
	}

	/** Returns true if field aBoolField is set (has been assigned a value) and false otherwise */
	public boolean isSetABoolField() {
		return EncodingUtils.testBit(__isset_bitfield, __ABOOLFIELD_ISSET_ID);
	}

	public void setABoolFieldIsSet(boolean value) {
		__isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ABOOLFIELD_ISSET_ID, value);
	}

	public TestingUnions getA_union() {
		return this.a_union;
	}

	public EventWrapper setA_union(TestingUnions a_union) {
		this.a_union = a_union;
		return this;
	}

	public void unsetA_union() {
		this.a_union = null;
	}

	/** Returns true if field a_union is set (has been assigned a value) and false otherwise */
	public boolean isSetA_union() {
		return this.a_union != null;
	}

	public void setA_unionIsSet(boolean value) {
		if (!value) {
			this.a_union = null;
		}
	}

	public String getTypedefOfTypedef() {
		return this.typedefOfTypedef;
	}

	public EventWrapper setTypedefOfTypedef(String typedefOfTypedef) {
		this.typedefOfTypedef = typedefOfTypedef;
		return this;
	}

	public void unsetTypedefOfTypedef() {
		this.typedefOfTypedef = null;
	}

	/** Returns true if field typedefOfTypedef is set (has been assigned a value) and false otherwise */
	public boolean isSetTypedefOfTypedef() {
		return this.typedefOfTypedef != null;
	}

	public void setTypedefOfTypedefIsSet(boolean value) {
		if (!value) {
			this.typedefOfTypedef = null;
		}
	}

	/**
	 * This is a docstring comment for a deprecated field that has been spread
	 * across two lines.
	 */
	@Deprecated
	public boolean isDepr() {
		return this.depr;
	}

	/**
	 * This is a docstring comment for a deprecated field that has been spread
	 * across two lines.
	 */
	@Deprecated
	public EventWrapper setDepr(boolean depr) {
		this.depr = depr;
		setDeprIsSet(true);
		return this;
	}

	@Deprecated
	public void unsetDepr() {
		__isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DEPR_ISSET_ID);
	}

	/** Returns true if field depr is set (has been assigned a value) and false otherwise */
	@Deprecated
	public boolean isSetDepr() {
		return EncodingUtils.testBit(__isset_bitfield, __DEPR_ISSET_ID);
	}

	@Deprecated
	public void setDeprIsSet(boolean value) {
		__isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DEPR_ISSET_ID, value);
	}

	@Deprecated
	public byte[] getDeprBinary() {
		setDeprBinary(org.apache.thrift.TBaseHelper.rightSize(deprBinary));
		return deprBinary == null ? null : deprBinary.array();
	}

	public java.nio.ByteBuffer bufferForDeprBinary() {
		return org.apache.thrift.TBaseHelper.copyBinary(deprBinary);
	}

	@Deprecated
	public EventWrapper setDeprBinary(byte[] deprBinary) {
		this.deprBinary = deprBinary == null ? (java.nio.ByteBuffer)null : java.nio.ByteBuffer.wrap(Arrays.copyOf(deprBinary, deprBinary.length));
		return this;
	}

	@Deprecated
	public EventWrapper setDeprBinary(java.nio.ByteBuffer deprBinary) {
		this.deprBinary = org.apache.thrift.TBaseHelper.copyBinary(deprBinary);
		return this;
	}

	@Deprecated
	public void unsetDeprBinary() {
		this.deprBinary = null;
	}

	/** Returns true if field deprBinary is set (has been assigned a value) and false otherwise */
	@Deprecated
	public boolean isSetDeprBinary() {
		return this.deprBinary != null;
	}

	@Deprecated
	public void setDeprBinaryIsSet(boolean value) {
		if (!value) {
			this.deprBinary = null;
		}
	}

	@Deprecated
	public int getDeprListSize() {
		return (this.deprList == null) ? 0 : this.deprList.size();
	}

	@Deprecated
	public java.util.Iterator<Boolean> getDeprListIterator() {
		return (this.deprList == null) ? null : this.deprList.iterator();
	}

	@Deprecated
	public void addToDeprList(boolean elem) {
		if (this.deprList == null) {
			this.deprList = new ArrayList<Boolean>();
		}
		this.deprList.add(elem);
	}

	@Deprecated
	public java.util.List<Boolean> getDeprList() {
		return this.deprList;
	}

	@Deprecated
	public EventWrapper setDeprList(java.util.List<Boolean> deprList) {
		this.deprList = deprList;
		return this;
	}

	@Deprecated
	public void unsetDeprList() {
		this.deprList = null;
	}

	/** Returns true if field deprList is set (has been assigned a value) and false otherwise */
	@Deprecated
	public boolean isSetDeprList() {
		return this.deprList != null;
	}

	@Deprecated
	public void setDeprListIsSet(boolean value) {
		if (!value) {
			this.deprList = null;
		}
	}

	public int getEventsDefaultSize() {
		return (this.EventsDefault == null) ? 0 : this.EventsDefault.size();
	}

	public java.util.Iterator<Event> getEventsDefaultIterator() {
		return (this.EventsDefault == null) ? null : this.EventsDefault.iterator();
	}

	public void addToEventsDefault(Event elem) {
		if (this.EventsDefault == null) {
			this.EventsDefault = new ArrayList<Event>();
		}
		this.EventsDefault.add(elem);
	}

	public java.util.List<Event> getEventsDefault() {
		return this.EventsDefault;
	}

	public EventWrapper setEventsDefault(java.util.List<Event> EventsDefault) {
		this.EventsDefault = EventsDefault;
		return this;
	}

	public void unsetEventsDefault() {
		this.EventsDefault = null;
	}

	/** Returns true if field EventsDefault is set (has been assigned a value) and false otherwise */
	public boolean isSetEventsDefault() {
		return this.EventsDefault != null;
	}

	public void setEventsDefaultIsSet(boolean value) {
		if (!value) {
			this.EventsDefault = null;
		}
	}

	public int getEventMapDefaultSize() {
		return (this.EventMapDefault == null) ? 0 : this.EventMapDefault.size();
	}

	public void putToEventMapDefault(long key, Event val) {
		if (this.EventMapDefault == null) {
			this.EventMapDefault = new HashMap<Long,Event>();
		}
		this.EventMapDefault.put(key, val);
	}

	public java.util.Map<Long, Event> getEventMapDefault() {
		return this.EventMapDefault;
	}

	public EventWrapper setEventMapDefault(java.util.Map<Long, Event> EventMapDefault) {
		this.EventMapDefault = EventMapDefault;
		return this;
	}

	public void unsetEventMapDefault() {
		this.EventMapDefault = null;
	}

	/** Returns true if field EventMapDefault is set (has been assigned a value) and false otherwise */
	public boolean isSetEventMapDefault() {
		return this.EventMapDefault != null;
	}

	public void setEventMapDefaultIsSet(boolean value) {
		if (!value) {
			this.EventMapDefault = null;
		}
	}

	public int getEventSetDefaultSize() {
		return (this.EventSetDefault == null) ? 0 : this.EventSetDefault.size();
	}

	public java.util.Iterator<Event> getEventSetDefaultIterator() {
		return (this.EventSetDefault == null) ? null : this.EventSetDefault.iterator();
	}

	public void addToEventSetDefault(Event elem) {
		if (this.EventSetDefault == null) {
			this.EventSetDefault = new HashSet<Event>();
		}
		this.EventSetDefault.add(elem);
	}

	public java.util.Set<Event> getEventSetDefault() {
		return this.EventSetDefault;
	}

	public EventWrapper setEventSetDefault(java.util.Set<Event> EventSetDefault) {
		this.EventSetDefault = EventSetDefault;
		return this;
	}

	public void unsetEventSetDefault() {
		this.EventSetDefault = null;
	}

	/** Returns true if field EventSetDefault is set (has been assigned a value) and false otherwise */
	public boolean isSetEventSetDefault() {
		return this.EventSetDefault != null;
	}

	public void setEventSetDefaultIsSet(boolean value) {
		if (!value) {
			this.EventSetDefault = null;
		}
	}

	public void setFieldValue(_Fields field, Object value) {
		switch (field) {
		case ID:
			if (value == null) {
				unsetID();
			} else {
				setID((Long)value);
			}
			break;

		case EV:
			if (value == null) {
				unsetEv();
			} else {
				setEv((Event)value);
			}
			break;

		case EVENTS:
			if (value == null) {
				unsetEvents();
			} else {
				setEvents((java.util.List<Event>)value);
			}
			break;

		case EVENTS2:
			if (value == null) {
				unsetEvents2();
			} else {
				setEvents2((java.util.Set<Event>)value);
			}
			break;

		case EVENT_MAP:
			if (value == null) {
				unsetEventMap();
			} else {
				setEventMap((java.util.Map<Long, Event>)value);
			}
			break;

		case NUMS:
			if (value == null) {
				unsetNums();
			} else {
				setNums((java.util.List<java.util.List<Integer>>)value);
			}
			break;

		case ENUMS:
			if (value == null) {
				unsetEnums();
			} else {
				setEnums((java.util.List<ItsAnEnum>)value);
			}
			break;

		case A_BOOL_FIELD:
			if (value == null) {
				unsetABoolField();
			} else {
				setABoolField((Boolean)value);
			}
			break;

		case A_UNION:
			if (value == null) {
				unsetA_union();
			} else {
				setA_union((TestingUnions)value);
			}
			break;

		case TYPEDEF_OF_TYPEDEF:
			if (value == null) {
				unsetTypedefOfTypedef();
			} else {
				setTypedefOfTypedef((String)value);
			}
			break;

		case DEPR:
			if (value == null) {
				unsetDepr();
			} else {
				setDepr((Boolean)value);
			}
			break;

		case DEPR_BINARY:
			if (value == null) {
				unsetDeprBinary();
			} else {
				setDeprBinary((java.nio.ByteBuffer)value);
			}
			break;

		case DEPR_LIST:
			if (value == null) {
				unsetDeprList();
			} else {
				setDeprList((java.util.List<Boolean>)value);
			}
			break;

		case EVENTS_DEFAULT:
			if (value == null) {
				unsetEventsDefault();
			} else {
				setEventsDefault((java.util.List<Event>)value);
			}
			break;

		case EVENT_MAP_DEFAULT:
			if (value == null) {
				unsetEventMapDefault();
			} else {
				setEventMapDefault((java.util.Map<Long, Event>)value);
			}
			break;

		case EVENT_SET_DEFAULT:
			if (value == null) {
				unsetEventSetDefault();
			} else {
				setEventSetDefault((java.util.Set<Event>)value);
			}
			break;

		}
	}

	public Object getFieldValue(_Fields field) {
		switch (field) {
		case ID:
			return getID();

		case EV:
			return getEv();

		case EVENTS:
			return getEvents();

		case EVENTS2:
			return getEvents2();

		case EVENT_MAP:
			return getEventMap();

		case NUMS:
			return getNums();

		case ENUMS:
			return getEnums();

		case A_BOOL_FIELD:
			return isABoolField();

		case A_UNION:
			return getA_union();

		case TYPEDEF_OF_TYPEDEF:
			return getTypedefOfTypedef();

		case DEPR:
			return isDepr();

		case DEPR_BINARY:
			return getDeprBinary();

		case DEPR_LIST:
			return getDeprList();

		case EVENTS_DEFAULT:
			return getEventsDefault();

		case EVENT_MAP_DEFAULT:
			return getEventMapDefault();

		case EVENT_SET_DEFAULT:
			return getEventSetDefault();

		}
		throw new IllegalStateException();
	}

	/** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
	public boolean isSet(_Fields field) {
		if (field == null) {
			throw new IllegalArgumentException();
		}

		switch (field) {
		case ID:
			return isSetID();
		case EV:
			return isSetEv();
		case EVENTS:
			return isSetEvents();
		case EVENTS2:
			return isSetEvents2();
		case EVENT_MAP:
			return isSetEventMap();
		case NUMS:
			return isSetNums();
		case ENUMS:
			return isSetEnums();
		case A_BOOL_FIELD:
			return isSetABoolField();
		case A_UNION:
			return isSetA_union();
		case TYPEDEF_OF_TYPEDEF:
			return isSetTypedefOfTypedef();
		case DEPR:
			return isSetDepr();
		case DEPR_BINARY:
			return isSetDeprBinary();
		case DEPR_LIST:
			return isSetDeprList();
		case EVENTS_DEFAULT:
			return isSetEventsDefault();
		case EVENT_MAP_DEFAULT:
			return isSetEventMapDefault();
		case EVENT_SET_DEFAULT:
			return isSetEventSetDefault();
		}
		throw new IllegalStateException();
	}

	@Override
	public boolean equals(Object that) {
		if (that == null)
			return false;
		if (that instanceof EventWrapper)
			return this.equals((EventWrapper)that);
		return false;
	}

	public boolean equals(EventWrapper that) {
		if (that == null)
			return false;
		if (this.isSetID() != that.isSetID() || this.ID != that.ID)
			return false;
		if (!Objects.equals(this.Ev, that.Ev))
			return false;
		if (!Objects.equals(this.Events, that.Events))
			return false;
		if (!Objects.equals(this.Events2, that.Events2))
			return false;
		if (!Objects.equals(this.EventMap, that.EventMap))
			return false;
		if (!Objects.equals(this.Nums, that.Nums))
			return false;
		if (!Objects.equals(this.Enums, that.Enums))
			return false;
		if (this.aBoolField != that.aBoolField)
			return false;
		if (!Objects.equals(this.a_union, that.a_union))
			return false;
		if (!Objects.equals(this.typedefOfTypedef, that.typedefOfTypedef))
			return false;
		if (this.depr != that.depr)
			return false;
		if (!Objects.equals(this.deprBinary, that.deprBinary))
			return false;
		if (!Objects.equals(this.deprList, that.deprList))
			return false;
		if (!Objects.equals(this.EventsDefault, that.EventsDefault))
			return false;
		if (!Objects.equals(this.EventMapDefault, that.EventMapDefault))
			return false;
		if (!Objects.equals(this.EventSetDefault, that.EventSetDefault))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		List<Object> list = new ArrayList<Object>();

		boolean present_ID = true && (isSetID());
		list.add(present_ID);
		if (present_ID)
			list.add(ID);

		boolean present_Ev = true && (isSetEv());
		list.add(present_Ev);
		if (present_Ev)
			list.add(Ev);

		boolean present_Events = true && (isSetEvents());
		list.add(present_Events);
		if (present_Events)
			list.add(Events);

		boolean present_Events2 = true && (isSetEvents2());
		list.add(present_Events2);
		if (present_Events2)
			list.add(Events2);

		boolean present_EventMap = true && (isSetEventMap());
		list.add(present_EventMap);
		if (present_EventMap)
			list.add(EventMap);

		boolean present_Nums = true && (isSetNums());
		list.add(present_Nums);
		if (present_Nums)
			list.add(Nums);

		boolean present_Enums = true && (isSetEnums());
		list.add(present_Enums);
		if (present_Enums)
			list.add(Enums);

		boolean present_aBoolField = true;
		list.add(present_aBoolField);
		if (present_aBoolField)
			list.add(aBoolField);

		boolean present_a_union = true && (isSetA_union());
		list.add(present_a_union);
		if (present_a_union)
			list.add(a_union);

		boolean present_typedefOfTypedef = true && (isSetTypedefOfTypedef());
		list.add(present_typedefOfTypedef);
		if (present_typedefOfTypedef)
			list.add(typedefOfTypedef);

		boolean present_depr = true;
		list.add(present_depr);
		if (present_depr)
			list.add(depr);

		boolean present_deprBinary = true && (isSetDeprBinary());
		list.add(present_deprBinary);
		if (present_deprBinary)
			list.add(deprBinary);

		boolean present_deprList = true && (isSetDeprList());
		list.add(present_deprList);
		if (present_deprList)
			list.add(deprList);

		boolean present_EventsDefault = true && (isSetEventsDefault());
		list.add(present_EventsDefault);
		if (present_EventsDefault)
			list.add(EventsDefault);

		boolean present_EventMapDefault = true && (isSetEventMapDefault());
		list.add(present_EventMapDefault);
		if (present_EventMapDefault)
			list.add(EventMapDefault);

		boolean present_EventSetDefault = true && (isSetEventSetDefault());
		list.add(present_EventSetDefault);
		if (present_EventSetDefault)
			list.add(EventSetDefault);

		return list.hashCode();
	}

	@Override
	public int compareTo(EventWrapper other) {
		if (!getClass().equals(other.getClass())) {
			return getClass().getName().compareTo(other.getClass().getName());
		}

		int lastComparison = 0;

		lastComparison = Boolean.compare(isSetID(), other.isSetID());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetID()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ID, other.ID);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetEv(), other.isSetEv());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetEv()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Ev, other.Ev);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetEvents(), other.isSetEvents());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetEvents()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Events, other.Events);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetEvents2(), other.isSetEvents2());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetEvents2()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Events2, other.Events2);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetEventMap(), other.isSetEventMap());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetEventMap()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.EventMap, other.EventMap);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetNums(), other.isSetNums());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetNums()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Nums, other.Nums);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetEnums(), other.isSetEnums());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetEnums()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Enums, other.Enums);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetABoolField(), other.isSetABoolField());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetABoolField()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.aBoolField, other.aBoolField);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetA_union(), other.isSetA_union());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetA_union()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.a_union, other.a_union);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetTypedefOfTypedef(), other.isSetTypedefOfTypedef());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetTypedefOfTypedef()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.typedefOfTypedef, other.typedefOfTypedef);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetDepr(), other.isSetDepr());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetDepr()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.depr, other.depr);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetDeprBinary(), other.isSetDeprBinary());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetDeprBinary()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deprBinary, other.deprBinary);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetDeprList(), other.isSetDeprList());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetDeprList()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deprList, other.deprList);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetEventsDefault(), other.isSetEventsDefault());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetEventsDefault()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.EventsDefault, other.EventsDefault);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetEventMapDefault(), other.isSetEventMapDefault());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetEventMapDefault()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.EventMapDefault, other.EventMapDefault);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.compare(isSetEventSetDefault(), other.isSetEventSetDefault());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetEventSetDefault()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.EventSetDefault, other.EventSetDefault);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		return 0;
	}

	public _Fields fieldForId(int fieldId) {
		return _Fields.findByThriftId(fieldId);
	}

	public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
		if (iprot.getScheme() != StandardScheme.class) {
			throw new UnsupportedOperationException();
		}
		new EventWrapperStandardScheme().read(iprot, this);
	}

	public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
		if (oprot.getScheme() != StandardScheme.class) {
			throw new UnsupportedOperationException();
		}
		new EventWrapperStandardScheme().write(oprot, this);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("EventWrapper(");
		boolean first = true;

		if (isSetID()) {
			sb.append("ID:");
			sb.append(this.ID);
			first = false;
		}
		if (!first) sb.append(", ");
		sb.append("Ev:");
		sb.append(this.Ev);
		first = false;
		if (!first) sb.append(", ");
		sb.append("Events:");
		sb.append(this.Events);
		first = false;
		if (!first) sb.append(", ");
		sb.append("Events2:");
		sb.append(this.Events2);
		first = false;
		if (!first) sb.append(", ");
		sb.append("EventMap:");
		sb.append(this.EventMap);
		first = false;
		if (!first) sb.append(", ");
		sb.append("Nums:");
		sb.append(this.Nums);
		first = false;
		if (!first) sb.append(", ");
		sb.append("Enums:");
		sb.append(this.Enums);
		first = false;
		if (!first) sb.append(", ");
		sb.append("aBoolField:");
		sb.append(this.aBoolField);
		first = false;
		if (!first) sb.append(", ");
		sb.append("a_union:");
		sb.append(this.a_union);
		first = false;
		if (!first) sb.append(", ");
		sb.append("typedefOfTypedef:");
		sb.append(this.typedefOfTypedef);
		first = false;
		if (!first) sb.append(", ");
		sb.append("depr:");
		sb.append(this.depr);
		first = false;
		if (!first) sb.append(", ");
		sb.append("deprBinary:");
		if (this.deprBinary == null) {
			sb.append("null");
		} else {
			org.apache.thrift.TBaseHelper.toString(this.deprBinary, sb);
		}
		first = false;
		if (!first) sb.append(", ");
		sb.append("deprList:");
		sb.append(this.deprList);
		first = false;
		if (isSetEventsDefault()) {
			if (!first) sb.append(", ");
			sb.append("EventsDefault:");
			sb.append(this.EventsDefault);
			first = false;
		}
		if (isSetEventMapDefault()) {
			if (!first) sb.append(", ");
			sb.append("EventMapDefault:");
			sb.append(this.EventMapDefault);
			first = false;
		}
		if (isSetEventSetDefault()) {
			if (!first) sb.append(", ");
			sb.append("EventSetDefault:");
			sb.append(this.EventSetDefault);
			first = false;
		}
		sb.append(")");
		return sb.toString();
	}

	public void validate() throws org.apache.thrift.TException {
		// check for required fields
		if (Ev == null) {
			throw new org.apache.thrift.protocol.TProtocolException("Required field 'Ev' is not present in struct 'EventWrapper'");
		}
		// check for sub-struct validity
		if (Ev != null) {
			Ev.validate();
		}
	}

	private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
		try {
			write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
		try {
			// it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
			__isset_bitfield = 0;
			read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private static class EventWrapperStandardScheme extends StandardScheme<EventWrapper> {

		public void read(org.apache.thrift.protocol.TProtocol iprot, EventWrapper struct) throws org.apache.thrift.TException {
			org.apache.thrift.protocol.TField schemeField;
			iprot.readStructBegin();
			while (true) {
				schemeField = iprot.readFieldBegin();
				if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
					break;
				}
				switch (schemeField.id) {
					case 1: // ID
						if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
							struct.ID = iprot.readI64();
							struct.setIDIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 2: // EV
						if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
							struct.Ev = new Event();
							struct.Ev.read(iprot);
							struct.setEvIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 3: // EVENTS
						if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
							org.apache.thrift.protocol.TList elem74 = iprot.readListBegin();
							struct.Events = new ArrayList<Event>(elem74.size);
							for (int elem75 = 0; elem75 < elem74.size; ++elem75) {
								Event elem76 = new Event();
								elem76.read(iprot);
								struct.Events.add(elem76);
							}
							iprot.readListEnd();
							struct.setEventsIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 4: // EVENTS2
						if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
							org.apache.thrift.protocol.TSet elem77 = iprot.readSetBegin();
							struct.Events2 = new HashSet<Event>(2*elem77.size);
							for (int elem78 = 0; elem78 < elem77.size; ++elem78) {
								Event elem79 = new Event();
								elem79.read(iprot);
								struct.Events2.add(elem79);
							}
							iprot.readSetEnd();
							struct.setEvents2IsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 5: // EVENT_MAP
						if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
							org.apache.thrift.protocol.TMap elem80 = iprot.readMapBegin();
							struct.EventMap = new HashMap<Long,Event>(2*elem80.size);
							for (int elem81 = 0; elem81 < elem80.size; ++elem81) {
								long elem83 = iprot.readI64();
								Event elem82 = new Event();
								elem82.read(iprot);
								struct.EventMap.put(elem83, elem82);
							}
							iprot.readMapEnd();
							struct.setEventMapIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 6: // NUMS
						if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
							org.apache.thrift.protocol.TList elem84 = iprot.readListBegin();
							struct.Nums = new ArrayList<java.util.List<Integer>>(elem84.size);
							for (int elem85 = 0; elem85 < elem84.size; ++elem85) {
								org.apache.thrift.protocol.TList elem87 = iprot.readListBegin();
								java.util.List<Integer> elem86 = new ArrayList<Integer>(elem87.size);
								for (int elem88 = 0; elem88 < elem87.size; ++elem88) {
									int elem89 = iprot.readI32();
									elem86.add(elem89);
								}
								iprot.readListEnd();
								struct.Nums.add(elem86);
							}
							iprot.readListEnd();
							struct.setNumsIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 7: // ENUMS
						if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
							org.apache.thrift.protocol.TList elem90 = iprot.readListBegin();
							struct.Enums = new ArrayList<ItsAnEnum>(elem90.size);
							for (int elem91 = 0; elem91 < elem90.size; ++elem91) {
								ItsAnEnum elem92 = ItsAnEnum.findByValue(iprot.readI32());
								struct.Enums.add(elem92);
							}
							iprot.readListEnd();
							struct.setEnumsIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 8: // A_BOOL_FIELD
						if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
							struct.aBoolField = iprot.readBool();
							struct.setABoolFieldIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 9: // A_UNION
						if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
							struct.a_union = new TestingUnions();
							struct.a_union.read(iprot);
							struct.setA_unionIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 10: // TYPEDEF_OF_TYPEDEF
						if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
							struct.typedefOfTypedef = iprot.readString();
							struct.setTypedefOfTypedefIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 11: // DEPR
						if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
							struct.depr = iprot.readBool();
							struct.setDeprIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 12: // DEPR_BINARY
						if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
							struct.deprBinary = iprot.readBinary();
							struct.setDeprBinaryIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 13: // DEPR_LIST
						if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
							org.apache.thrift.protocol.TList elem93 = iprot.readListBegin();
							struct.deprList = new ArrayList<Boolean>(elem93.size);
							for (int elem94 = 0; elem94 < elem93.size; ++elem94) {
								boolean elem95 = iprot.readBool();
								struct.deprList.add(elem95);
							}
							iprot.readListEnd();
							struct.setDeprListIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 14: // EVENTS_DEFAULT
						if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
							org.apache.thrift.protocol.TList elem96 = iprot.readListBegin();
							struct.EventsDefault = new ArrayList<Event>(elem96.size);
							for (int elem97 = 0; elem97 < elem96.size; ++elem97) {
								Event elem98 = new Event();
								elem98.read(iprot);
								struct.EventsDefault.add(elem98);
							}
							iprot.readListEnd();
							struct.setEventsDefaultIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 15: // EVENT_MAP_DEFAULT
						if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
							org.apache.thrift.protocol.TMap elem99 = iprot.readMapBegin();
							struct.EventMapDefault = new HashMap<Long,Event>(2*elem99.size);
							for (int elem100 = 0; elem100 < elem99.size; ++elem100) {
								long elem102 = iprot.readI64();
								Event elem101 = new Event();
								elem101.read(iprot);
								struct.EventMapDefault.put(elem102, elem101);
							}
							iprot.readMapEnd();
							struct.setEventMapDefaultIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 16: // EVENT_SET_DEFAULT
						if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
							org.apache.thrift.protocol.TSet elem103 = iprot.readSetBegin();
							struct.EventSetDefault = new HashSet<Event>(2*elem103.size);
							for (int elem104 = 0; elem104 < elem103.size; ++elem104) {
								Event elem105 = new Event();
								elem105.read(iprot);
								struct.EventSetDefault.add(elem105);
							}
							iprot.readSetEnd();
							struct.setEventSetDefaultIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					default:
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
				}
				iprot.readFieldEnd();
			}
			iprot.readStructEnd();

			// check for required fields of primitive type, which can't be checked in the validate method
			struct.validate();
		}

		public void write(org.apache.thrift.protocol.TProtocol oprot, EventWrapper struct) throws org.apache.thrift.TException {
			struct.validate();

			oprot.writeStructBegin(STRUCT_DESC);
			if (struct.isSetID()) {
				oprot.writeFieldBegin(ID_FIELD_DESC);
				long elem106 = struct.ID;
				oprot.writeI64(elem106);
				oprot.writeFieldEnd();
			}
			if (struct.isSetEv()) {
				oprot.writeFieldBegin(EV_FIELD_DESC);
				struct.Ev.write(oprot);
				oprot.writeFieldEnd();
			}
			if (struct.isSetEvents()) {
				oprot.writeFieldBegin(EVENTS_FIELD_DESC);
				oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.Events.size()));
				for (Event elem107 : struct.Events) {
					elem107.write(oprot);
				}
				oprot.writeListEnd();
				oprot.writeFieldEnd();
			}
			if (struct.isSetEvents2()) {
				oprot.writeFieldBegin(EVENTS2_FIELD_DESC);
				oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, struct.Events2.size()));
				for (Event elem108 : struct.Events2) {
					elem108.write(oprot);
				}
				oprot.writeSetEnd();
				oprot.writeFieldEnd();
			}
			if (struct.isSetEventMap()) {
				oprot.writeFieldBegin(EVENT_MAP_FIELD_DESC);
				oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I64, org.apache.thrift.protocol.TType.STRUCT, struct.EventMap.size()));
				for (Map.Entry<Long, Event> elem109 : struct.EventMap.entrySet()) {
					long elem110 = elem109.getKey();
					oprot.writeI64(elem110);
					elem109.getValue().write(oprot);
				}
				oprot.writeMapEnd();
				oprot.writeFieldEnd();
			}
			if (struct.isSetNums()) {
				oprot.writeFieldBegin(NUMS_FIELD_DESC);
				oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.Nums.size()));
				for (java.util.List<Integer> elem111 : struct.Nums) {
					oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, elem111.size()));
					for (int elem112 : elem111) {
						int elem113 = elem112;
						oprot.writeI32(elem113);
					}
					oprot.writeListEnd();
				}
				oprot.writeListEnd();
				oprot.writeFieldEnd();
			}
			if (struct.isSetEnums()) {
				oprot.writeFieldBegin(ENUMS_FIELD_DESC);
				oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.Enums.size()));
				for (ItsAnEnum elem114 : struct.Enums) {
					ItsAnEnum elem115 = elem114;
					oprot.writeI32(elem115.getValue());
				}
				oprot.writeListEnd();
				oprot.writeFieldEnd();
			}
			oprot.writeFieldBegin(A_BOOL_FIELD_FIELD_DESC);
			boolean elem116 = struct.aBoolField;
			oprot.writeBool(elem116);
			oprot.writeFieldEnd();
			if (struct.isSetA_union()) {
				oprot.writeFieldBegin(A_UNION_FIELD_DESC);
				struct.a_union.write(oprot);
				oprot.writeFieldEnd();
			}
			if (struct.isSetTypedefOfTypedef()) {
				oprot.writeFieldBegin(TYPEDEF_OF_TYPEDEF_FIELD_DESC);
				String elem117 = struct.typedefOfTypedef;
				oprot.writeString(elem117);
				oprot.writeFieldEnd();
			}
			oprot.writeFieldBegin(DEPR_FIELD_DESC);
			boolean elem118 = struct.depr;
			oprot.writeBool(elem118);
			oprot.writeFieldEnd();
			if (struct.isSetDeprBinary()) {
				oprot.writeFieldBegin(DEPR_BINARY_FIELD_DESC);
				java.nio.ByteBuffer elem119 = struct.deprBinary;
				oprot.writeBinary(elem119);
				oprot.writeFieldEnd();
			}
			if (struct.isSetDeprList()) {
				oprot.writeFieldBegin(DEPR_LIST_FIELD_DESC);
				oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.BOOL, struct.deprList.size()));
				for (boolean elem120 : struct.deprList) {
					boolean elem121 = elem120;
					oprot.writeBool(elem121);
				}
				oprot.writeListEnd();
				oprot.writeFieldEnd();
			}
			if (struct.isSetEventsDefault()) {
				oprot.writeFieldBegin(EVENTS_DEFAULT_FIELD_DESC);
				oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.EventsDefault.size()));
				for (Event elem122 : struct.EventsDefault) {
					elem122.write(oprot);
				}
				oprot.writeListEnd();
				oprot.writeFieldEnd();
			}
			if (struct.isSetEventMapDefault()) {
				oprot.writeFieldBegin(EVENT_MAP_DEFAULT_FIELD_DESC);
				oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I64, org.apache.thrift.protocol.TType.STRUCT, struct.EventMapDefault.size()));
				for (Map.Entry<Long, Event> elem123 : struct.EventMapDefault.entrySet()) {
					long elem124 = elem123.getKey();
					oprot.writeI64(elem124);
					elem123.getValue().write(oprot);
				}
				oprot.writeMapEnd();
				oprot.writeFieldEnd();
			}
			if (struct.isSetEventSetDefault()) {
				oprot.writeFieldBegin(EVENT_SET_DEFAULT_FIELD_DESC);
				oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, struct.EventSetDefault.size()));
				for (Event elem125 : struct.EventSetDefault) {
					elem125.write(oprot);
				}
				oprot.writeSetEnd();
				oprot.writeFieldEnd();
			}
			oprot.writeFieldStop();
			oprot.writeStructEnd();
		}

	}

}
